"""Pydantic schemas for TOON format objects."""

from typing import Any, Dict, List, Literal, Optional
from pydantic import BaseModel, Field


class PanelSpec(BaseModel):
    """Specification for a visualization panel."""

    type: Literal[
        "bar", "line", "stat", "table", "pie", "gauge",
        "heatmap", "histogram", "state_timeline", "status_history",
        "candlestick", "trend", "xy", "bar_gauge"
    ] = "bar"
    title: str = ""
    description: Optional[str] = None  # Annotation/Explanation
    sql: Optional[str] = None  # Panel-specific SQL
    x: Optional[str] = None  # X-axis column for charts
    y: Optional[str] = None  # Y-axis column for charts
    group_by: Optional[str] = Field(None, alias="groupBy")
    columns: Optional[List[str]] = None  # For table type
    value: Optional[str] = None  # For stat/gauge type
    unit: Optional[str] = None

    model_config = {"populate_by_name": True}


class QuerySpec(BaseModel):
    """Specification for a SQL query."""

    sql: str
    params: Optional[Dict[str, Any]] = None


class DashboardSpec(BaseModel):
    """Specification for a Grafana dashboard."""

    title: str
    panels: List[PanelSpec] = Field(default_factory=list)
    refresh: str = "5s"
    time_from: str = Field("now-1h", alias="timeFrom")
    time_to: str = Field("now", alias="timeTo")

    model_config = {"populate_by_name": True}


class AnalyticalPlan(BaseModel):
    """An analytical plan generated by the question compiler."""

    question: str = Field(..., alias="q")
    feasible: bool = True
    reason: Optional[str] = None  # Explanation if not feasible
    tables: List[str] = Field(default_factory=list)
    sql: Optional[str] = None  # Main SQL (legacy/primary)
    viz: Optional[List[PanelSpec]] = None  # List of panels for the dashboard
    dashboard: Optional[DashboardSpec] = None
    follow_up: Optional[List[str]] = Field(None, alias="followUp")
    suggested_investigations: Optional[List[str]] = Field(None, alias="suggestedInvestigations")  # Ranked hypotheses

    model_config = {"populate_by_name": True}


class SchemaProfile(BaseModel):
    """Profile of a table schema for LLM context."""

    table: str
    columns: List[Dict[str, str]]  # [{name, type, description}]
    row_count: int = Field(0, alias="rowCount")
    sample_values: Optional[Dict[str, List[Any]]] = Field(None, alias="sampleValues")

    model_config = {"populate_by_name": True}


class RefusalResponse(BaseModel):
    """Response when a question cannot be answered."""

    question: str = Field(..., alias="q")
    feasible: bool = False
    reason: str
    missing_data: Optional[List[str]] = Field(None, alias="missingData")
    suggestions: Optional[List[str]] = None
